@startuml
left to right direction
' class 会社()
' class 社員()
' ' 会社 --> 社員:雇う
' 会社"1"--"*" 社員
' note top of 会社:雇用者
' note top of 社員:従業員


' left to right direction
' 会員リストo-- 会員
' note right of 会員リスト
' 会員クラスがなくて成り立つ
' end note
left to right direction
パソコン"1" *-- ハードディスク
note right of パソコン
ハードディスクがないと成り立ちません。
end note
@enduml

