@startuml
skinparam classAttributeIconSize 0
class A <<stereotype>> {}
class B {
- 属性1:int
- 属性2:String
}
class C {
---
+ 操作1():void
+ 操作2():String
}
class D {
- 属性1:int
- 属性2:String
---
+ 操作1():void
+ 操作2():String
}
' hide A circle
' hide B circle
' hide C circle
' hide D circle

skinparam classAttributeIconSize 0
class Employee{
- id:int=0
- name:String
#depertoment:String
/連続年数:int
---
+setid(id:int):void
+getid():int
+setname(name:String):void
+getName(name:String):void
+setdept(dept:String):void
+getdept():String
}
hide Employee circle
@enduml
@enduml