@startuml 例題3-1
skinparam classAttributeIconSize 0
class 空軍リスト{

-管理番号:string
}
class 車{
---
- 車体番号:string
- 車種:string
- 駆動方式:stirng
}
class 顧客{
- 顧客ID:stirng
- 氏名:string
- 電話番号:string
- 郵便番号:string
- 住所:string
---
+ setName(氏名:string) void
}
class 予約{
    - 予約番号:stirng
    - 管理番号:string
    - 顧客ID:string
    - 予約日:string
}
class 貸出{
    - 貸出番号:string
    - 管理番号:string
    - 顧客ID:string
    - 予約日:string
}

@enduml