@startuml ラーメン屋さんでの注文
hide footbox
actor 客 as guest
participant ":フロア店員" as clerk
participant ":料理人" as cooker
activate guest
guest -> clerk:ラーメンを注文する
activate clerk
clerk -> cooker:両理を指示する
activate cooker
cooker ->cooker:料理をする
clerk <<-- cooker:ラーメン
deactivate cooker
deactivate clerk
guest <<-- clerk:ラーメン
deactivate guest
@enduml