@startuml 診察予約
[*] -right->メニュー
state メニュー{
}
state 予約と確認{
}
state あなたの順番{
}
state 今の順番{
}

メニュー -down-> 予約と確認 : 予約と確認へを押す
予約と確認 -up-> メニュー : 取消を押す

予約と確認 -right-> あなたの順番 : 登録を押す
予約と確認 -right-> あなたの順番 : 確認を押す
あなたの順番 -up-> メニュー :　メニューへを押す
メニュー -down-> 今の順番 : 今の順番へを押す
今の順番 -up-> メニュー : メニューへを押す
メニュー -right-> [*]
@enduml