@startuml ユースケース図
left to right direction
actor 人事担当者 #DDDDDD;line:black;line.bold;
actor 従業員 #DDDDDD;line:black;line.bold;
rectangle 従業員登録システム{
    usecase 社員情報を参照する 
    usecase 社員情報登録する 
    usecase 社員情報を修正する
}
従業員 --> 社員情報を参照する
人事担当者--> 社員情報を修正する
人事担当者 --> 社員情報登録する
人事担当者 --|> 従業員
@enduml