@startuml 演習7-3_AC_レストランのアクティビティ図
|顧客|
:案内を依頼する;
|給仕|
:テーブルにご案内する;
:メニュー表を渡す;
:メニュー]
|顧客|
:呼び鈴を押す]
|給仕|
:顧客のところに行く]
|顧客|
:注文を伝える]
|給仕|
:注文を受ける
:注文を料理人に伝える]
|料理人|
:注文を受ける;
:料理を作る;
:料理]
fork
|給仕|
:料理を運ぶ;
:料理]
fork again
:伝票を渡す;
:伝票]
end fork
|顧客|
:料理を食べる;
:代金を支払う;

stop
@enduml