@startuml クラス図
    left to right direction
    class 注文明細{
        - 合計:int
    }

    class 注文{
        - 数量:int
        - 小計:int
    }

    class 割引クーポン{
        - 値引き額:int
        - 期限:String
    }

    class 商品{
        - 名称:String
        - 単価:int
    }

    class カップ{
        - サイズ:String
    }

    class ドリンク{
        - 種別:String
    }

    class フード{
    }

    class ポテト{
    }

    class 材料{
    }

    class ハンバーガー{
        - 種別:String
    }

    class レシピ{
        - サイズ:String
    }

    class パン{
    }

    class 肉{
    }

    class 野菜{
    }

    class チーズ{
    }
    
    注文明細 o-- 注文 : 1...*
    注文 "0...*"--"0...1" 割引クーポン
    注文 "0...*"--"1" 商品
    ドリンク -up-|> 商品
    ドリンク "1...3"--"0...*" カップ
    フード -up-|> 商品
    フード "1"--"1" ポテト
    ハンバーガー -up-|> フード
    レシピ -up-|> フード
    材料 --o ハンバーガー : 1...*
    パン -up-|> 材料
    肉 -up-|> 材料
    野菜 -up-|> 材料
    チーズ -up-|> 材料
@enduml