@startuml アクティビティ図
title A社の全体業務

|営業部門|
start
:発注;

    |販売代理店|
    :受注;
    :在庫調査;
    if () then (在庫なし)
        :;
        note right
            作図の都合上、
            ダミーの
            アクティビティ
            を記述
        end note
    else (在庫あり)
        |製造部門|
        :製造;
    endif

|販売代理店|
:発送;

|営業部門|
:検収/支払い;

|販売代理店|
:入金確認;

stop
@enduml